GEOS-ESM/circleci-tools

.editorconfig, .github/workflows/changelog-enforcer.yml, CHANGELOG.md, CONTRIBUTING.md, COPYRIGHT, LICENSE, README-ORIG.md, src/@orb.yml, src/commands/buildinstall.yml, src/commands/checkout_branch_on_fixture.yml, src/commands/checkout_fixture.yml, src/commands/checkout_mapl_branch.yml, src/commands/cmake.yml, src/commands/compress_artifacts.yml, src/commands/mepoclone.yml, src/commands/mepodevelop.yml, src/commands/versions.yml
This PR is my first attempt at this. It adds the commands from the MAPL CI into an orb.
=> [semver:patch] Add MAPL CI Commands

CHANGELOG.md, src/commands/buildinstall.yml, src/commands/checkout_branch_on_fixture.yml, src/commands/checkout_fixture.yml, src/commands/checkout_mapl_branch.yml, src/commands/cmake.yml, src/commands/mepoclone.yml, src/commands/mepodevelop.yml
In order to make things cleaner, let's make GEOSgcm the default repo
=> [semver:minor] Set GEOSgcm as default repo

CHANGELOG.md, src/executors/README-ORIG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/ifort.yml
This PR adds in the two executors we use in GEOS CI.
=> [semver:minor] Add gfortran and ifort executors

CHANGELOG.md, src/commands/checkout_branch_on_subrepo.yml, src/commands/mepodevelop.yml
This will allow us to do `mepo checkout branch repo` on more repos.
=> [semver:minor] Add command to mepo checkout branch on subrepos

CHANGELOG.md, src/commands/checkout_if_exists.yml
This PR fixes an edge case in the `checkout-if-exists` command
=> [semver:minor] Fix for checkout-if-exists bug

CHANGELOG.md, src/commands/run_tutorial.yml, src/jobs/run_mapl_tutorial.yml
This adds commands to try and run MAPL tutorials
=> [semver:minor] Add job and command for MAPL tutorials

CHANGELOG.md, src/executors/README.md, src/executors/gfortran-bcs.yml, src/executors/gfortran.yml, src/executors/ifort-bcs.yml, src/executors/ifort.yml, src/jobs/build.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This updates the default compilers, baselibs, and bcs version.
=> [semver:minor] Update default compiler, baselibs, and bcs version

CHANGELOG.md, README.md
This PR just updates the README to better reflect how things work in orb-tools v11 land.
=> Update README for v11 orb-tools workflow

CHANGELOG.md, src/commands/cmake.yml, src/jobs/build.yml, src/jobs/run_fv3.yml
This PR adds the ability to pass in `fv_precision` to the cmake step in builds
=> Add ability to pass in fv_precision to builds

CHANGELOG.md, src/commands/buildinstall.yml, src/commands/buildtarget.yml, src/commands/buildtests.yml, src/commands/cmake.yml, src/commands/create_gcm_expt.yml, src/executors/README.md, src/executors/gfortran-bcs.yml, src/executors/ifort-bcs.yml, src/jobs/build.yml, src/jobs/run_gcm.yml, src/scripts/greet.sh
This PR adds the ability to use Ninja as a CMake Generator.
=> Add Ninja ability

CHANGELOG.md, src/executors/docker.yml, src/jobs/publish-docker.yml
This PR adds a job to build and publish a docker image.
=> Add docker publish job

CHANGELOG.md, src/jobs/publish-docker.yml
We need to append the compiler name to image as we might build both Intel and GNU
=> Append compiler name to image

CHANGELOG.md, src/commands/create_gcm_expt.yml, src/jobs/run_gcm.yml
This PR adds support to pass in ocean type to experiments.
=> Add support to pass in ocean type

CHANGELOG.md, src/commands/run_gcm_experiment.yml
=> Fix typo in run command

CHANGELOG.md, src/executors/README.md, src/executors/gfortran-bcs.yml, src/executors/gfortran.yml, src/executors/ifort-bcs.yml, src/executors/ifort.yml, src/jobs/build.yml, src/jobs/publish-docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR updates the CI to use Baselibs 7.17.0 by default
=> Update to Baselibs 7.17.0

CHANGELOG.md, src/examples/README.md, src/examples/build_geosgcm_with_commands.yml, src/examples/build_geosgcm_with_job.yml
This PR just fixes up the examples to reflect the snake_case from circleci-tools v2 (aka orb-tools v12)
=> Update examples for v2

CHANGELOG.md, src/commands/mepoclone.yml, src/jobs/build.yml
The purpose of this PR is add an option to perform blobless mepo clones of of GEOSgcm.
=> Add Blobless Mepo Clone

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
Oddities are appearing with Baselibs 7.24 and GCC 13. For now, revert back to 7.23
=> Revert back to Baselib 7.23

CHANGELOG.md, src/examples/build_geosgcm_with_commands.yml, src/examples/build_geosgcm_with_job.yml, src/executors/README.md, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This is an attempt to add an `ifx` executor for the Baselibs v7 branch. Additional changes will be needed in geos-build-env that makes the Docker images.
https://github.com/GMAO-SI-Team/geos-build-env/pull/2
=> Add ifx executor (v4)

CHANGELOG.md, src/examples/build_geosgcm_with_commands.yml, src/examples/build_geosgcm_with_job.yml, src/executors/README.md, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This is an attempt to add an `ifx` executor. Additional changes will be needed in geos-build-env that makes the Docker images.
https://github.com/GMAO-SI-Team/geos-build-env/pull/2
=> Add ifx executor

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This updates the default Baselibs to v7.27.0
=> v4: Update to Baselibs 7.27.0 default

CHANGELOG.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/publish_docker.yml
This PR is an attempt to move to use Ubuntu 24 by default in CI images.
=> v4: Move to Ubuntu 24

CHANGELOG.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/publish_docker.yml
This PR is an attempt to move to use Ubuntu 24 by default in CI images.
=> v5: Move to Ubuntu 24

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
Move to use Baselibs 7.29.0 by default
=> v4: Update to Baselibs 7.29.0 default

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR updates the default Baselibs to 7.31.0
=> v4: Update default Baselibs to 7.31.0

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
Update Baselibs default to v8.11.0
=> v5: Update default Baselibs to 8.11.0

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
=> v5: Update default Baselibs to 8.13.0

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
Update Baselibs to 7.33.0 for ESMF 8.8.1
=> v4: Update default Baselibs to 7.33.0

CHANGELOG.md, src/executors/ifx.yml, src/executors/ifx_bcs.yml
=> v4: Update to ifx 2025.1
