GEOS-ESM/circleci-tools

CHANGELOG.md, src/executors/docker.yml, src/jobs/publish-docker.yml
This PR moves to use the `machine` executor for Docker builds
=> Use machine executor for Docker builds

CHANGELOG.md, src/jobs/publish-docker.yml
We need to be able to pass in the BCs version for GEOSgcm builds.
=> Add bcs_version to docker build job

CHANGELOG.md, src/jobs/build.yml
For coupled runs, we need to persist the `install/coupled_diagnostics` directory. 
Adding on `post` since I see these (not important) lines:
```
/bin/cp: cannot stat '/root/project/workspace/install-GEOSgcm/post/plot.rc': No such file or directory
/bin/cp: cannot stat '/root/project/workspace/install-GEOSgcm/post/post.rc': No such file or directory
```
=> Add post and coupled_diagnostics to workspace

CHANGELOG.md, src/commands/run_makeoneday.yml
This PR adds a `change_layout` boolean to makeoneday because MOM6 runs do not handle that well. I should fix makeoneday, but for now, this is a good workaround.
=> Add change_layout boolean to makeoneday

CHANGELOG.md, src/executors/README.md, src/executors/gfortran-bcs.yml, src/executors/gfortran.yml, src/executors/ifort-bcs.yml, src/executors/ifort.yml, src/jobs/build.yml, src/jobs/publish-docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR moves the circleci-tools orb to use Baselibs 7.7.0 by default.
=> Move to Baselibs 7.7.0 by default

CHANGELOG.md, src/executors/README.md, src/executors/gfortran-bcs.yml, src/executors/gfortran.yml, src/executors/ifort-bcs.yml, src/executors/ifort.yml, src/jobs/build.yml, src/jobs/publish-docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
As the title says, update to use Baselibs v7.13.0 and BCs v11.1.0 by default.
=> Update to Baselibs v7.13.0 and BCs v11.1.0 by default

CHANGELOG.md, src/executors/README.md, src/executors/gfortran-bcs.yml, src/executors/ifort-bcs.yml, src/jobs/run_gcm.yml
As it says, we update the default BCs to v11.3.0. This is because MOM6 runs need a new file
=> Update default BCs to v11.3.0

.circleci/config.yml, .circleci/test-deploy.yml, CHANGELOG.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml
Due to changes in MAPL, we need to move to Open MPI 5 to avoid a conflict between `MPI_THREAD_MULTIPLE` and the pt2pt OSC.
=> Update to Open MPI 5.0.0 with GNU

CHANGELOG.md, src/commands/checkout_feature_branch_on_fixture_allow_fail.yml, src/jobs/build.yml
This PR attempts to add the ability to checkout a PR's branch on the fixture before doing `mepo clone` this is used in PRs like https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/872 where the model can't build because `main` on GEOSgcm does not have needed repos.
=> Add ability to try and checkout the PR branch on fixture

CHANGELOG.md, src/executors/docker.yml
Due to [Linux image deprecations by CircleCI](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177), this PR updates the docker executor to use the `default` machine image.
=> Update docker executor

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This updates the CI to use Baselibs 7.23.0 by default. This matches moves made in GEOSgcm
=> Update to Baselibs 7.23.0

CHANGELOG.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml
This PR moves circleci-tools to use GCC 13 images by default.
=> Move to GCC 13

CHANGELOG.md, src/jobs/build.yml
The GEOSldas workflow uses a `BRIDGE` branch instead of standard GitFlow. After the split out of GEOSldas_GridComp, this exposed an issue because *both* GEOSldas and GEOSldas_GridComp could have `BRIDGE` branches that aren't quite in sync. 
So, this PR gives the ability to disable the `mepo checkout-if-exists` step, though we default to `true`.
=> Add option to disable checkout-if-exists

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR moves the orb to use Baselibs 7.24 by default.
=> Update to use Baselibs 7.24.0 by default

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR updates the orb to use Baselibs 8.0.2 by default.
This brings in FMS-in-Baselibs
=> Update CI to use Baselibs 8.0.2 by default

CHANGELOG.md, src/executors/README.md, src/executors/gfortran_bcs.yml, src/executors/ifort_bcs.yml, src/jobs/run_gcm.yml
This update moves the v2 circleci-tools to use BCs v11.5.0 by default
=> Update to v11.5.0 BCs by default (v2)

CHANGELOG.md, src/executors/README.md, src/executors/gfortran_bcs.yml, src/executors/ifort_bcs.yml, src/jobs/run_gcm.yml
This update updates the default bcs to v11.5.0 as a hope to fix an issue with CI
=> Update to v11.5.0 BCs by default

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR updates the default Baselibs in the v2 series of circleci-tools to Baselibs 7.25.0.
ETA: Moving to draft. Testing with MAPL has found an issue.
=> v2: Update default Baselibs to 7.25.0

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR updates the orb to Baselibs 8.5.0 as well as moving the default Intel versions to ifort 2021.13 and Intel MPI 2021.13
=> Update to Baselibs 8.5.0, Intel 2021.13 and Intel MPI 2021.13

CHANGELOG.md, src/executors/README.md, src/executors/gfortran_bcs.yml, src/executors/ifort_bcs.yml, src/jobs/run_gcm.yml
This updates the default BCs to v11.6.0. This is mainly for R21C work, but might as well update it for future work as well.
=> v2: Update default BCs to v11.6.0

CHANGELOG.md, src/executors/README.md, src/executors/gfortran_bcs.yml, src/executors/ifort_bcs.yml, src/jobs/run_gcm.yml
This updates the default BCs to v11.6.0. This is mainly for R21C work, but might as well update it for future work as well.
=> Update default BCs to v11.6.0

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR moves the orb to use Baselibs 8.6.0 by default
=> Update to Baselibs 8.6.0 by default

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This moves the v5 orb to use Baselibs 8.7.0 by default
=> v5: Update to Baselibs 8.7.0 default

CHANGELOG.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml
This PR updates v5 orb to use GCC 14 in the GCC executors
=> v5: Update to GCC 14 in GCC executors

CHANGELOG.md, src/jobs/build.yml
An edge case was found where a commit to MAPL created a CMake failure when building without pFUnit. This will let us test that case.
=> v5: Add remove_pfunit option

CHANGELOG.md, src/executors/ifx.yml, src/executors/ifx_bcs.yml
This PR updates the ifx executor to use ifx 2025.0 and Intel MPI 2021.14
=> v4: Update to ifx 2025.0

CHANGELOG.md, src/executors/ifx.yml, src/executors/ifx_bcs.yml
This PR updates the ifx executor to use ifx 2025.0 and Intel MPI 2021.14
=> v5: Update to ifx 2025.0

CHANGELOG.md, src/jobs/build.yml
This PR updates v4 to use the `xlarge` resource class for build jobs. This is needed for `ifx` CI testing it was found.
=> v4: Use xlarge by default for builds

CHANGELOG.md, src/jobs/build.yml
This PR updates v4 to use the `xlarge` resource class for build jobs. This is needed for `ifx` CI testing it was found.
=> v5: Use xlarge by default for builds

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR moves v5 to use Baselibs 8.9.0 (aka ESMF 8.8.0) by default
=> v5: Update to Baselibs 8.9.0 default

CHANGELOG.md, src/jobs/run_mapl_tutorial.yml
This adds the ability to use `build_type` matrices with `run_mapl_tutorial`
=> v4: Add build_type to run_mapl_tutorial

CHANGELOG.md, src/jobs/run_mapl_tutorial.yml
This adds the ability to use `build_type` matrices with `run_mapl_tutorial`
=> v5: Add build_type to run_mapl_tutorial

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
There was an issue in v8.11.0 so we move to 8.12.0
=> v5: Update default Baselibs to 8.12.0

CHANGELOG.md, src/jobs/build.yml
Revert back to `large` executor for builds. Saves on cost.
=> v4: Revert to large executor for builds

CHANGELOG.md, src/jobs/build.yml
Revert back to large executor for builds. Saves on cost.
=> v5: Revert to large executor for builds

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR updates v5 to use Baselibs 8.14.0 by default.
The main purpose is to get ESMF 8.8.1 in here.
=> v5: Update default Baselibs to 8.14.0

CHANGELOG.md, src/commands/create_gcm_expt.yml, src/jobs/run_gcm.yml
Recently GEOSgcm v12 has reverted to the v12 BCs. We need to update the orb.
=> v5: Revert to v12 land bcs

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR updates the v4 branch of circleci-tools to Baselibs 8.18.0 by default
=> v4: Update to Baselibs 8.18.0 by default

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR updates to Baselibs 8.19.0 by default which has ESMF v9.0.0b03
NOTE: This should be used with MAPL 2.61+
=> v4: Update to Baselibs 8.19.0 by default

CHANGELOG.md, src/executors/README.md, src/executors/gfortran.yml, src/executors/gfortran_bcs.yml, src/executors/ifort.yml, src/executors/ifort_bcs.yml, src/executors/ifx.yml, src/executors/ifx_bcs.yml, src/jobs/build.yml, src/jobs/publish_docker.yml, src/jobs/run_fv3.yml, src/jobs/run_gcm.yml, src/jobs/run_mapl_tutorial.yml
This PR updates to Baselibs 8.19.0 by default which has ESMF v9.0.0b03
NOTE: This should be used with MAPL 2.61+
=> v5: Update to Baselibs 8.19.0 by default
